name: Run Python Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run amalgamation
      run: python Amalgamation.py

    - name: Commit and push if changes
      run: |
        git config --global user.email "gerren.14@gmail.com"
        git config --global user.name "CookiedOutMonster"
        git add EmbedDB.c
        git add EmbedDB.h
        git diff --staged --quiet || (git commit -m "Amalgamated source files" && git push)
