name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-linters:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Lint
        run: clang-format -n --Werror

  build:
    name: Build and Run Tests
    runs-on: windows-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    continue-on-error: true

    steps:
    - uses: actions/checkout@v3

    - name: Build and Run
      run: make test

    - name: Publish Unit Test Results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      with:
        github_token: ${{ github.token }}
        files: ./build/results/*.xml
        check_name: Unit Test Results
