name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v3

    - name: Build and Run
      run: make test

    - name: Publish Unit Test Results
      if: always()
      uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1.9
      with:
        github_token: ${{ github.token }}
        files: ./*.xml
        check_name: Unit Test Results
        comment_on_pr: true
